### PR TITLE
Move CI to github actions

### PR DESCRIPTION
**Pull request by dralley**

### CODE REVIEW

**Comment by dralley** [comment]
Successful CI run here: https://github.com/dralley/librpm.rs/actions/runs/1430752365

**Comment by tarcieri** [comment]
Looks good to me, but we need to remove the mandatory check for Travis CI and I don't have access to do that /cc @Conan-Kudo

**Comment by Conan-Kudo** [comment]
Fixed, and now I'll merge it. 😉

**Review by Conan-Kudo — APPROVED** [review]

**Comment by tarcieri** [comment]
Thank you!

**Pull request merged**
